# Generated by Django 5.1.4 on 2024-12-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reta',
            new_name='rate',
        ),
    ]
