# Generated by Django 5.1.4 on 2024-12-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_tag_post_category_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Tag',
            new_name='title',
        ),
    ]
